[package]
name = "golana"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

 
[dependencies]
anchor-lang = "0.25.0"
solana-program = "1.10.41"
borsh = "0.9.3" 

[dependencies.goscript-vm] 
path = "../../goscript/vm"
features = ["btree_map"]
version = "0.1.0"
